DrDab/BreakfastBookClub

frontend/src/FirebaseConfig.js, frontend/src/webapp/pages/LogIn.js
=> fixed login

frontend/src/App.js, frontend/src/tests/pages/BookClub.test.js, frontend/src/tests/pages/Home.test.js, frontend/src/tests/pages/SearchResults.test.js, frontend/src/tests/pages/UserProfile.test.js, frontend/src/webapp/components/AppBars/LoggedInAppBar.js, frontend/src/webapp/components/Banners/UserProfileBanner.js, frontend/src/webapp/components/Constants.js, frontend/src/webapp/components/CreatePost.js, frontend/src/webapp/components/Lists/NotificationList.js, frontend/src/webapp/components/Lists/PeopleList.js, frontend/src/webapp/pages/BookClub.js, frontend/src/webapp/pages/Home.js, frontend/src/webapp/pages/LogIn.js, frontend/src/webapp/pages/SearchResults.js, frontend/src/webapp/pages/UserProfile.js
All user profiles link to firebase token and breakfastbookclub database.
=> Add get user api route to frontend

frontend/src/App.css, frontend/src/webapp/components/AppBars/LoggedInAppBar.js, frontend/src/webapp/components/Banners/BookClubBanner.js, frontend/src/webapp/components/Lists/BookList.js, frontend/src/webapp/components/Lists/NotificationList.js, frontend/src/webapp/components/Lists/PostList.js, frontend/src/webapp/components/Utils.js, frontend/src/webapp/pages/BookClub.js
the frontend calls get_book whenever user navigates to a book profile page.
=> added get book route to frontend

frontend/src/webapp/components/Banners/UserProfileBanner.js, frontend/src/webapp/components/CreatePost.js, frontend/src/webapp/pages/BookClub.js, frontend/src/webapp/pages/Home.js, frontend/src/webapp/pages/UserProfile.js
Added get_post by book club and user.
Window does not reload for every POST call, API refetches.
=> added get_post by book club and user

frontend/src/tests/pages/BookClub.test.js, frontend/src/tests/pages/Home.test.js, frontend/src/tests/pages/Login.test.js, frontend/src/tests/pages/SearchResults.test.js, frontend/src/tests/pages/SignUp.test.js, frontend/src/tests/pages/UserProfile.test.js
- added tests for user profile, book club, search results pages
- cleaned up code for home, login, sign up pages
=> added tests to all main pages

backend/BCAPIServer/src/main/java/BCServerMain.java, backend/BCAPIServer/src/main/java/daos/Books.java, backend/BCAPIServer/src/main/java/daos/Posts.java, backend/BCAPIServer/src/main/java/daos/User.java, backend/BCAPIServer/src/main/java/routes/bookclubs/GetLikedPosts.java, backend/BCAPIServer/src/main/java/routes/bookclubs/GetMembers.java, backend/BCAPIServer/src/main/java/routes/bookclubs/GetPosts.java, backend/BCAPIServer/src/main/java/routes/bookclubs/MakePost.java, backend/BCAPIServer/src/main/java/routes/bookclubs/UnlikePost.java, backend/BCAPIServer/src/main/java/utils/BCGsonUtils.java, backend/BCAPIServer/src/main/java/utils/ResultSetParsers.java, database/Create_Tables.sql
- Reimplemented LikePost with adjacency list
- Implemented UnlikePost
- Implemented GetLikedPosts for user
- Reimplemented GetMembers using user profile JSON objects instead of UID's
=> Week 7 Victor backend API additions

frontend/src/tests/pages/BookClub.test.js, frontend/src/webapp/components/Banners/UserProfileBanner.js, frontend/src/webapp/components/Lists/PeopleList.js, frontend/src/webapp/pages/BookClub.js, frontend/src/webapp/pages/Home.js, frontend/src/webapp/pages/UserProfile.js
Set up frontend for:
- GetMembers (of book club)
- JoinClub (lets users join a club)
- UnjoinClub (lets users unjoin a club)
- GetSubscribedClubs (gets clubs subscribed by user) 
- ListFriends (lists friends of user - as User JSON Object specified in API doc)
- AddFriend (lets user friend another user)
- RemoveFriend (lets user unfriend another user, if they are already friends)
=> Frontend api setup

backend/BCAPIServer/src/main/java/BCServerMain.java, frontend/src/tests/pages/BookClub.test.js, frontend/src/tests/pages/Home.test.js, frontend/src/tests/pages/SearchResults.test.js, frontend/src/tests/pages/UserProfile.test.js, frontend/src/webapp/components/Lists/PostList.js, frontend/src/webapp/components/Post.js, frontend/src/webapp/pages/BookClub.js, frontend/src/webapp/pages/Home.js, frontend/src/webapp/pages/SearchResults.js, frontend/src/webapp/pages/UserProfile.js
Added LikePost, UnlikePost, and GetLikedPosts to frontend
=> added like posts to frontend

frontend/src/tests/pages/BookClub.test.js, frontend/src/webapp/components/Lists/BookList.js, frontend/src/webapp/components/Lists/PeopleList.js, frontend/src/webapp/components/Lists/PostList.js, frontend/src/webapp/components/Post.js, frontend/src/webapp/pages/BookClub.js
added get_members api route to frontend
=> Frontend get members

backend/BCAPIServer/src/main/java/BCServerMain.java, backend/BCAPIServer/src/main/java/daos/User.java, backend/BCAPIServer/src/main/java/routes/bookclubs/GetIsUserLikedPost.java, frontend/src/webapp/components/Constants.js, frontend/src/webapp/components/Lists/PostList.js, frontend/src/webapp/components/Post.js, frontend/src/webapp/pages/BookClub.js, frontend/src/webapp/pages/Home.js, frontend/src/webapp/pages/UserProfile.js
closes https://github.com/DrDab/BreakfastBookClub/issues/29
get_is_user_liked_post returns 1 or 0.
mainly uses the getNumLikesFromUser() function
=> get is user liked post

frontend/src/tests/pages/BookClub.test.js, frontend/src/webapp/components/AppBars/LoggedInAppBar.js, frontend/src/webapp/components/Banners/BookClubBanner.js, frontend/src/webapp/components/Lists/NotificationList.js
Set up frontend code to send and get recommendations
Recommend modal frontend
Will send  this json object
=> Frontend send rec setup

frontend/src/webapp/components/Banners/BookClubBanner.js, frontend/src/webapp/pages/BookClub.js, frontend/src/webapp/pages/UserProfile.js
more set up for get friends and post recommendations api routes
=> more set up for friends and recs api routes

frontend/src/tests/pages/BookClub.test.js, frontend/src/tests/pages/UserProfile.test.js, frontend/src/webapp/components/Banners/BookClubBanner.js, frontend/src/webapp/components/Lists/BookList.js, frontend/src/webapp/pages/BookClub.js, frontend/src/webapp/pages/Home.js, frontend/src/webapp/pages/SearchResults.js, frontend/src/webapp/pages/UserProfile.js
get saved books 
recognizes that animal farm is a saved book
=> Frontend save books get saved books

backend/BCAPIServer/src/main/java/routes/bookclubs/GetRecommendations.java, frontend/src/tests/pages/BookClub.test.js, frontend/src/webapp/components/AppBars/LoggedInAppBar.js, frontend/src/webapp/components/Banners/BookClubBanner.js, frontend/src/webapp/components/Lists/NotificationList.js
Added  recommend_book and get_recommendations to frontend
=> frontend recommend_book, get_recommendations

backend/BCAPIServer/src/main/java/BCServerMain.java, backend/BCAPIServer/src/main/java/daos/Books.java, backend/BCAPIServer/src/main/java/routes/bookmgmt/UnsaveBook.java
=> finished  unsave book but i need to test it first

frontend/src/tests/pages/BookClub.test.js, frontend/src/tests/pages/Home.test.js, frontend/src/tests/pages/UserProfile.test.js, frontend/src/webapp/components/AppBars/LoggedInAppBar.js, frontend/src/webapp/components/Banners/BookClubBanner.js, frontend/src/webapp/components/Banners/UserProfileBanner.js, frontend/src/webapp/components/CreatePost.js, frontend/src/webapp/components/Lists/NotificationList.js, frontend/src/webapp/components/Utils.js, frontend/src/webapp/pages/BookClub.js, frontend/src/webapp/pages/Home.js, frontend/src/webapp/pages/SearchResults.js, frontend/src/webapp/pages/UserProfile.js
=> Clean up fetch

frontend/src/tests/pages/BookClub.test.js, frontend/src/tests/pages/Home.test.js, frontend/src/tests/pages/UserProfile.test.js, frontend/src/webapp/components/Banners/BookClubBanner.js, frontend/src/webapp/components/Banners/UserProfileBanner.js, frontend/src/webapp/components/Lists/NotificationList.js, frontend/src/webapp/components/Utils.js
=> added unsave_book to frontend

backend/BCAPIServer/src/main/java/BCServerMain.java, backend/BCAPIServer/src/main/java/daos/User.java, backend/BCAPIServer/src/main/java/routes/bookclubs/DeleteRecommendation.java
finished delete recommendation
=> Jocies branch

frontend/src/webapp/components/AppBars/LoggedInAppBar.js, frontend/src/webapp/components/Banners/BookClubBanner.js, frontend/src/webapp/components/Banners/UserProfileBanner.js, frontend/src/webapp/components/Lists/PostList.js, frontend/src/webapp/components/Post.js, frontend/src/webapp/pages/BookClub.js, frontend/src/webapp/pages/Home.js, frontend/src/webapp/pages/UserProfile.js
added delete post route to frontend
=> frontend delete post

backend/BCAPIServer/src/main/java/routes/bookclubs/DeletePost.java, backend/BCAPIServer/src/main/java/routes/bookclubs/DeleteRecommendation.java, backend/BCAPIServer/src/main/java/routes/bookmgmt/GetSaveBooks.java, frontend/src/tests/pages/BookClub.test.js, frontend/src/tests/pages/UserProfile.test.js, frontend/src/webapp/components/AppBars/LoggedInAppBar.js, frontend/src/webapp/components/Banners/BookClubBanner.js, frontend/src/webapp/components/Lists/NotificationList.js, frontend/src/webapp/components/Notification.js, frontend/src/webapp/components/Post.js, frontend/src/webapp/pages/BookClub.js, frontend/src/webapp/pages/UserProfile.js
Added delete notifs to frontend
=> Frontend delete notifs

frontend/src/webapp/components/AppBars/LoggedInAppBar.js, frontend/src/webapp/components/Lists/NotificationList.js, frontend/src/webapp/components/Lists/PostList.js, frontend/src/webapp/components/Notification.js, frontend/src/webapp/components/Post.js, frontend/src/webapp/pages/BookClub.js, frontend/src/webapp/pages/Home.js, frontend/src/webapp/pages/UserProfile.js
- reduces number of refetches
- looks like post and notification was automatically deleted
=> display none when notification or post is deleted

frontend/src/tests/pages/BookClub.test.js, frontend/src/tests/pages/Home.test.js, frontend/src/tests/pages/UserProfile.test.js, frontend/src/webapp/components/Banners/UserProfileBanner.js, frontend/src/webapp/components/Lists/PeopleList.js, frontend/src/webapp/pages/BookClub.js, frontend/src/webapp/pages/Home.js, frontend/src/webapp/pages/UserProfile.js
added list_friends, add_friend, remove_friend to frontend.
=> Frontend friends

backend/BCAPIServer/src/main/java/BCServerMain.java, backend/BCAPIServer/src/main/java/daos/User.java, backend/BCAPIServer/src/main/java/routes/bookclubs/GetSubscribedClubs.java, backend/BCAPIServer/src/main/java/routes/bookclubs/JoinClub.java, backend/BCAPIServer/src/main/java/routes/bookclubs/UnjoinClub.java
I wrote API routes for joining club, leaving club and getting a user's clubs. Can someone code review this please?
=> Club ap iroutes

backend/BCAPIServer/src/main/java/BCServerMain.java, backend/BCAPIServer/src/main/java/daos/User.java, backend/BCAPIServer/src/main/java/routes/bookclubs/GetPosts.java, backend/BCAPIServer/src/main/java/routes/bookclubs/GetSubscribedClubs.java, backend/BCAPIServer/src/main/java/routes/bookclubs/JoinClub.java, backend/BCAPIServer/src/main/java/routes/bookclubs/UnjoinClub.java, frontend/src/tests/pages/BookClub.test.js, frontend/src/tests/pages/Home.test.js, frontend/src/tests/pages/UserProfile.test.js, frontend/src/webapp/components/CreatePost.js, frontend/src/webapp/components/Lists/BookList.js, frontend/src/webapp/components/Lists/PeopleList.js, frontend/src/webapp/components/Lists/PostList.js, frontend/src/webapp/pages/BookClub.js, frontend/src/webapp/pages/Home.js, frontend/src/webapp/pages/UserProfile.js
added join, un-join, get subscribed clubs to frontend
@ZaynabKhan 
I replaced token with user_id for the param on get_subscribed _clubs and fixed the join/unjoin routes by changing 
IS_CLUB_MEMBER = "SELECT COUNT(*) FROM user_clubs WHERE user_id = ? AND book_key = ?" -->
IS_CLUB_MEMBER = "SELECT COUNT(*) AS count FROM user_clubs WHERE user_id = ? AND book_key = ?" 
This was causing the 500 server error
=> added join, un-join, get user joined clubs

backend/BCAPIServer/src/main/java/routes/usersearch/UserSearch.java, frontend/src/tests/pages/SearchResults.test.js, frontend/src/webapp/components/AppBars/LoggedInAppBar.js, frontend/src/webapp/components/Banners/UserProfileBanner.js, frontend/src/webapp/components/CreatePost.js, frontend/src/webapp/components/Lists/PeopleList.js, frontend/src/webapp/components/Notification.js, frontend/src/webapp/components/Post.js, frontend/src/webapp/components/Utils.js, frontend/src/webapp/pages/Home.js, frontend/src/webapp/pages/SearchResults.js, frontend/src/webapp/pages/UserProfile.js
Main: Added search_users to frontend, improved user search query
Additions: Made all avatars uppercase, refetch friends like on add or remove
=> Frontend search users

frontend/src/webapp/components/AppBars/LoggedInAppBar.js, frontend/src/webapp/components/Banners/UserProfileBanner.js, frontend/src/webapp/components/Utils.js, frontend/src/webapp/pages/BookClub.js, frontend/src/webapp/pages/Home.js, frontend/src/webapp/pages/LogIn.js, frontend/src/webapp/pages/SearchResults.js, frontend/src/webapp/pages/SignUp.js, frontend/src/webapp/pages/UserProfile.js
changed avatar colors, cleaned up code
=> changed avatar colors, cleaned up code

frontend/src/App.css, frontend/src/tests/pages/Home.test.js, frontend/src/webapp/components/Banners/BookClubBanner.js, frontend/src/webapp/components/Lists/ListItems/Post.js, frontend/src/webapp/components/Lists/PostList.js, frontend/src/webapp/pages/BookClub.js, frontend/src/webapp/pages/Home.js, frontend/src/webapp/pages/LogIn.js, frontend/src/webapp/pages/SearchResults.js, frontend/src/webapp/pages/SignUp.js, frontend/src/webapp/pages/UserProfile.js
- added delete post modal
- discover new posts
=> added delete post modal, discover new posts

frontend/src/webapp/components/Lists/ListItems/Post.js
Not needed because get_posts is fast enough
=> removed display none

frontend/src/App.js, frontend/src/index.js, frontend/src/tests/pages/SearchResults.test.js, frontend/src/webapp/components/AppBars/LoggedInAppBar.js, frontend/src/webapp/components/CreatePost.js, frontend/src/webapp/components/Lists/BookList.js, frontend/src/webapp/components/Lists/ListItems/Notification.js, frontend/src/webapp/components/Lists/ListItems/Post.js, frontend/src/webapp/components/Lists/PeopleList.js, frontend/src/webapp/pages/SearchResults.js
get search term from url instead of session storage
=> Frontend search results

frontend/package-lock.json, frontend/package.json, frontend/src/index.js
added code to deploy to gh pages
=> set up for gh pages
